import postSignupRoute from "./routes/signup";
import getLoginRoute from "./routes/login";
import productRoute from "./routes/product";
import userRoute from "./routes/user";
import express, { Application } from "express";
import cors from "cors";
import cartRoutes from "./routes/order";

const bodyParser = require("body-parser");
const app: Application = express();
app.use(cors());
app.use(express.json());
app.use(cors());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(cartRoutes);
app.use(postSignupRoute);
app.use(getLoginRoute);
app.use(productRoute);
app.use(userRoute);
export default app;
